language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - chmod +x gradlew
  - mkdir ~/.gradle
  - echo "bintrayUser=" > ~/.gradle/gradle.properties
  - echo "bintrayPass=" >> ~/.gradle/gradle.properties