language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - mkdir -p ~/.gradle
  - echo "bintrayUser=" > ~/.gradle/gradle.properties
  - echo "bintrayPass=" >> ~/.gradle/gradle.properties